"""admin panel

Revision ID: eab4e10a9c4d
Revises: 6861a75aa3d6
Create Date: 2026-09-04 12:30:36.742614
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eab4e10a9c4d'
down_revision: Union[str, None] = '6861a75aa3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'unpaid', 'paid', 'overdue', 'void', name='invoicestatus'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_due_on'), 'invoices', ['due_on'], unique=False)
    op.create_index(op.f('ix_invoices_facility_id'), 'invoices', ['facility_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_issued_on'), 'invoices', ['issued_on'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('method_type', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_facility_id'), 'payment_methods', ['facility_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_table('staff_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_notes_facility_id'), 'staff_notes', ['facility_id'], unique=False)
    op.create_index(op.f('ix_staff_notes_id'), 'staff_notes', ['id'], unique=False)
    op.create_index(op.f('ix_staff_notes_staff_id'), 'staff_notes', ['staff_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_id'), 'invoice_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('staff_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_reviews_facility_id'), 'staff_reviews', ['facility_id'], unique=False)
    op.create_index(op.f('ix_staff_reviews_id'), 'staff_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_staff_reviews_staff_id'), 'staff_reviews', ['staff_id'], unique=False)
    op.create_table('booking_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('author_side', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_messages_application_id'), 'booking_messages', ['application_id'], unique=False)
    op.create_index(op.f('ix_booking_messages_id'), 'booking_messages', ['id'], unique=False)
    op.add_column('facilities', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('facilities', sa.Column('description', sa.Text(), nullable=True))
    # server_default so the ALTER succeeds on tables that already have rows;
    # existing members become managers, the least-privileged sensible default.
    # The default is kept (and declared on the model) rather than dropped —
    # SQLite cannot DROP DEFAULT, and a DB-side default is harmless here.
    op.add_column(
        'facility_members',
        sa.Column(
            'facility_role',
            sa.Enum('super_admin', 'manager', 'staff', name='facilityrole'),
            nullable=False,
            server_default='manager',
        ),
    )
    op.add_column('facility_members', sa.Column('permissions', sa.String(length=255), nullable=True))
    op.add_column('facility_members', sa.Column('invited_by_id', sa.Integer(), nullable=True))
    op.add_column('facility_members', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))

    # batch_alter_table so this works on SQLite too, which cannot ALTER a
    # constraint in place and needs Alembic's copy-and-move strategy. The
    # foreign key is named explicitly: an unnamed one cannot be dropped later.
    with op.batch_alter_table('facility_members') as batch:
        batch.create_unique_constraint(
            'uq_member_facility_user', ['facility_id', 'user_id']
        )
        batch.create_foreign_key(
            'fk_facility_members_invited_by', 'users',
            ['invited_by_id'], ['id'], ondelete='SET NULL',
        )
    op.add_column('shifts', sa.Column('overtime_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('shifts', sa.Column('required_qualifications', sa.String(length=255), nullable=True))
    op.add_column('shifts', sa.Column('required_certifications', sa.String(length=255), nullable=True))
    op.add_column(
        'shifts',
        sa.Column('is_visible', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column('shifts', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shifts', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shifts', sa.Column('cancellation_reason', sa.String(length=255), nullable=True))

    # MySQL stores an ENUM as a column type, so a new member needs an explicit
    # ALTER — autogenerate does not detect added enum values. Other dialects
    # (SQLite in tests) store it as VARCHAR + CHECK and need nothing.
    if op.get_bind().dialect.name == 'mysql':
        op.execute(
            "ALTER TABLE shifts MODIFY COLUMN status "
            "ENUM('draft','open','filled','completed','cancelled') NOT NULL"
        )

    # Shifts that existed before drafts did were, by definition, published.
    op.execute(
        "UPDATE shifts SET published_at = created_at WHERE published_at IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == 'mysql':
        op.execute("UPDATE shifts SET status = 'cancelled' WHERE status = 'draft'")
        op.execute(
            "ALTER TABLE shifts MODIFY COLUMN status "
            "ENUM('open','filled','completed','cancelled') NOT NULL"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'cancellation_reason')
    op.drop_column('shifts', 'cancelled_at')
    op.drop_column('shifts', 'published_at')
    op.drop_column('shifts', 'is_visible')
    op.drop_column('shifts', 'required_certifications')
    op.drop_column('shifts', 'required_qualifications')
    op.drop_column('shifts', 'overtime_rate')
    with op.batch_alter_table('facility_members') as batch:
        batch.drop_constraint('fk_facility_members_invited_by', type_='foreignkey')
        batch.drop_constraint('uq_member_facility_user', type_='unique')
    op.drop_column('facility_members', 'accepted_at')
    op.drop_column('facility_members', 'invited_by_id')
    op.drop_column('facility_members', 'permissions')
    op.drop_column('facility_members', 'facility_role')
    op.drop_column('facilities', 'description')
    op.drop_column('facilities', 'contact_email')
    op.drop_index(op.f('ix_booking_messages_id'), table_name='booking_messages')
    op.drop_index(op.f('ix_booking_messages_application_id'), table_name='booking_messages')
    op.drop_table('booking_messages')
    op.drop_index(op.f('ix_staff_reviews_staff_id'), table_name='staff_reviews')
    op.drop_index(op.f('ix_staff_reviews_id'), table_name='staff_reviews')
    op.drop_index(op.f('ix_staff_reviews_facility_id'), table_name='staff_reviews')
    op.drop_table('staff_reviews')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_staff_notes_staff_id'), table_name='staff_notes')
    op.drop_index(op.f('ix_staff_notes_id'), table_name='staff_notes')
    op.drop_index(op.f('ix_staff_notes_facility_id'), table_name='staff_notes')
    op.drop_table('staff_notes')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_facility_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issued_on'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_facility_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_on'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
